<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="2" failed="1" skipped="4">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-18T10:27:18Z" name="Suite" finished-at="2022-08-18T10:27:51Z" duration-ms="33226">
    <groups>
    </groups>
    <test started-at="2022-08-18T10:27:18Z" name="Test" finished-at="2022-08-18T10:27:51Z" duration-ms="33226">
      <class name="com.test.classes.MyTestClass">
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:18Z" name="initializeDriver" finished-at="2022-08-18T10:27:20Z" duration-ms="2425" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="getMovieReleaseDateFromIMDB()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:20Z" name="getMovieReleaseDateFromIMDB" finished-at="2022-08-18T10:27:36Z" duration-ms="15563" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getMovieReleaseDateFromIMDB -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:36Z" name="quitDriver" finished-at="2022-08-18T10:27:36Z" duration-ms="389" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:36Z" name="initializeDriver" finished-at="2022-08-18T10:27:37Z" duration-ms="1252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="getMovieReleaseDateFromWikipedia()[pri:1, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:37Z" name="getMovieReleaseDateFromWikipedia" finished-at="2022-08-18T10:27:42Z" duration-ms="5214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getMovieReleaseDateFromWikipedia -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:42Z" name="quitDriver" finished-at="2022-08-18T10:27:43Z" duration-ms="206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:43Z" name="initializeDriver" finished-at="2022-08-18T10:27:44Z" duration-ms="1175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="assertExtractedDetails()[pri:2, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:44Z" name="assertExtractedDetails" finished-at="2022-08-18T10:27:44Z" duration-ms="7" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [17 December 2021] but found [January 7, 2022 (United States)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [17 December 2021] but found [January 7, 2022 (United States)]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.test.classes.MyTestClass.assertExtractedDetails(MyTestClass.java:102)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertExtractedDetails -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:44Z" name="quitDriver" finished-at="2022-08-18T10:27:44Z" duration-ms="463" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:44Z" name="initializeDriver" finished-at="2022-08-18T10:27:46Z" duration-ms="1347" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="assertExtractedDetails()[pri:2, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:46Z" name="assertExtractedDetails" finished-at="2022-08-18T10:27:46Z" duration-ms="4" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [17 December 2021] but found [January 7, 2022 (United States)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [17 December 2021] but found [January 7, 2022 (United States)]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.test.classes.MyTestClass.assertExtractedDetails(MyTestClass.java:102)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertExtractedDetails -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:46Z" name="quitDriver" finished-at="2022-08-18T10:27:46Z" duration-ms="370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:46Z" name="initializeDriver" finished-at="2022-08-18T10:27:47Z" duration-ms="1230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="assertExtractedDetails()[pri:2, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:47Z" name="assertExtractedDetails" finished-at="2022-08-18T10:27:47Z" duration-ms="1" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [17 December 2021] but found [January 7, 2022 (United States)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [17 December 2021] but found [January 7, 2022 (United States)]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.test.classes.MyTestClass.assertExtractedDetails(MyTestClass.java:102)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertExtractedDetails -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:47Z" name="quitDriver" finished-at="2022-08-18T10:27:48Z" duration-ms="356" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:48Z" name="initializeDriver" finished-at="2022-08-18T10:27:49Z" duration-ms="1277" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="assertExtractedDetails()[pri:2, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:49Z" name="assertExtractedDetails" finished-at="2022-08-18T10:27:49Z" duration-ms="3" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [17 December 2021] but found [January 7, 2022 (United States)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [17 December 2021] but found [January 7, 2022 (United States)]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.test.classes.MyTestClass.assertExtractedDetails(MyTestClass.java:102)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertExtractedDetails -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:49Z" name="quitDriver" finished-at="2022-08-18T10:27:49Z" duration-ms="221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:49Z" name="initializeDriver" finished-at="2022-08-18T10:27:50Z" duration-ms="1134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="assertExtractedDetails()[pri:2, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:50Z" name="assertExtractedDetails" finished-at="2022-08-18T10:27:50Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [17 December 2021] but found [January 7, 2022 (United States)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [17 December 2021] but found [January 7, 2022 (United States)]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.test.classes.MyTestClass.assertExtractedDetails(MyTestClass.java:102)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertExtractedDetails -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:com.test.classes.MyTestClass@6d167f58]" started-at="2022-08-18T10:27:50Z" name="quitDriver" finished-at="2022-08-18T10:27:51Z" duration-ms="515" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.test.classes.MyTestClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
